# This file is used to configure the JDK version used by the Gradle Daemon (Build Runtime)
# This configuration wins over the JAVA_HOME environment variable and NEWT's configurations
# This doesn't just affect JDK used by Gradle but also same JDK is used by Ant for the production classes so
# it needs to match with toolchains in build.gradle
toolchainVersion=21
toolchainVendor=azul