// Netflix internal overrides to
// https://github.com/Netflix/spectator/blob/main/spectator-ext-jvm/src/main/resources/cassandra.conf
netflix.spectator.agent.jmx.mappings = ${?netflix.spectator.agent.jmx.mappings} [
  {
    query = "org.apache.cassandra.metrics:type=*ColumnFamily,name=UnrepairedAgeInSeconds,keyspace=*,*"
    measurements = [
      {
        name = "cass.cf.{name}"
        tags = [
          {
            key = "scope"
            value = "{scope}"
          },
          {
            key = "keyspace"
            value = "{keyspace}"
          },
          {
            key = "atlas.dstype"
            value = "gauge"
          }
        ]
        value = "{Value}"
      }
    ]
  },

  {
    query = "org.apache.cassandra.net:type=Gossiper"
    measurements = [
      {
        name = "cass.health.schemaCount"
        tags = [
          {
            key = "atlas.dstype"
            value = "gauge"
          }
        ]
        value = "{SchemaVersionCount}"
      }
      {
        name = "cass.health.tokensState"
        tags = [
          {
            key = "atlas.dstype"
            value = "gauge"
          }
        ]
        value = "{TokenOwnershipHash}"
      }
    ]
  }
]
