netflix.spectator.agent.jmx.mappings = ${?netflix.spectator.agent.jmx.mappings} [
  {
    query = "org.apache.cassandra.net:type=Gossiper"
    measurements = [
      {
        name = "cass.health.schemaCount"
        tags = [
          {
            key = "atlas.dstype"
            value = "gauge"
          }
        ]
        value = "{SchemaVersionCount}"
      }
      {
        name = "cass.health.tokensState"
        tags = [
          {
            key = "atlas.dstype"
            value = "gauge"
          }
        ]
        value = "{TokenOwnershipHash}"
      }
    ]
  }
]